## Import Libraries

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

from tqdm import tqdm
import random

import re

## Load Data

In [2]:
#Just like file_path = '../../Data/split_3.parquet', there are split_1.parquet through split_6.parquet, all of which should be concatenated into one df called apps
apps = pd.DataFrame()
for n in range(1,7):
    file_path = f'../../Data/split_{n}.parquet'
    apps = pd.concat([apps, pd.read_parquet(file_path)])
apps

,OpportunityId,ApplicationId,ExternalBriefDescription,ExternalDescription,Title,JobCategoryName,IsRejected,IsCandidateInternal,BehaviorCriteria,MotivationCriteria,...,Educations,LicenseAndCertifications,Skills,Motivations,Behaviors,StepId,StepName,Tag,StepGroup,pass_first_step
0,MbzeABKVn06G8irkoHJeIg==,nTzdqGj020CYqTouPocGSg==,"$16.00 Per Hour\n\nAt Orkin, our purpose is to...",<p><strong>$16.00 Per Hour</strong></p>\n<p><s...,Customer Service Specialist,Customer Service,True,False,None,None,...,None,None,None,None,None,K8yQlic+/UiXxBMpOnAoLQ==,Decline,2.0,declined,False
1,7SPt0A57/kyzM9hE9vxDRg==,QVk5MFCZ70WvlZE9FzAW9g==,"$15.00 Per Hour\n\nAt Orkin, our purpose is to...",<p><strong>$15.00 Per Hour</strong></p>\n<p><s...,Customer Service Specialist,Customer Service,True,False,None,None,...,None,None,None,None,None,K8yQlic+/UiXxBMpOnAoLQ==,Decline,2.0,declined,False
2,7SPt0A57/kyzM9hE9vxDRg==,I1kcPlAw3E+rqceh0qrutQ==,"$15.00 Per Hour\n\nAt Orkin, our purpose is to...",<p><strong>$15.00 Per Hour</strong></p>\n<p><s...,Customer Service Specialist,Customer Service,True,False,None,None,...,None,None,None,None,None,K8yQlic+/UiXxBMpOnAoLQ==,Decline,2.0,declined,False
3,zolSWBFjWESbfkj8AXLYwA==,VTCXZK6/ZUWJDpxTcm2CRg==,"$15.00 Per Hour\n\nAt Orkin, our purpose is to...",<p><strong>$15.00 Per Hour</strong></p>\n<p><s...,Customer Service Specialist,Customer Service,True,False,None,None,...,None,None,None,None,None,K8yQlic+/UiXxBMpOnAoLQ==,Decline,2.0,declined,False
4,zolSWBFjWESbfkj8AXLYwA==,I6KgcL0jdkG8wBnL1+BZ/g==,"$15.00 Per Hour\n\nAt Orkin, our purpose is to...",<p><strong>$15.00 Per Hour</strong></p>\n<p><s...,Customer Service Specialist,Customer Service,True,False,None,None,...,None,None,None,None,None,K8yQlic+/UiXxBMpOnAoLQ==,Decline,2.0,declined,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110262,PNL1Y3XJ50Whs9uchKxtyA==,URO0MqU14Eys5V5BrxL0qQ==,Berkshire is a national management company tha...,<p><strong><em>Team &ldquo;IT FACTOR&rdquo;</e...,Property Manager,Property Management,True,False,None,None,...,None,None,None,None,None,BGEezloW4EGuGdzEobmLsw==,Being Reviewed,NaN,other,True
110263,rWGGQMet/0GjOg8+J2MD0w==,8XKm6D+2KkiPHO3XTUXkcA==,Berkshire Communities is a national management...,<p><strong><em>Team &ldquo;IT FACTOR&rdquo;</e...,Property Manager,Property Management,True,False,None,None,...,None,None,None,None,None,S69pj47jM0mAb/Ne6i6goA==,Decline,2.0,declined,False
110264,rWGGQMet/0GjOg8+J2MD0w==,dYTPtlNw+UChHEl50M5Xag==,Berkshire Communities is a national management...,<p><strong><em>Team &ldquo;IT FACTOR&rdquo;</e...,Property Manager,Property Management,True,False,None,None,...,None,None,None,None,None,S69pj47jM0mAb/Ne6i6goA==,Decline,2.0,declined,False
110265,xNgzKlWSDkCoWpgBGmXmrA==,9cBFQH7OGEO/kHUFL9d2DA==,Berkshire is a national management company tha...,<p><strong><em>Team &ldquo;IT FACTOR&rdquo;</e...,Property Manager - Future Acquisition Opportunity,Property Management,False,False,None,None,...,None,None,None,[],[],wyObdVyxxEOkwTIQsnAS3A==,Under Qualified,NaN,declined,False
110266,FIfUhm23tU+CmoaUCQOfEA==,Q/UZxlNiJkC4/3QOZdEEeQ==,Berkshire Communities is a national management...,<p><strong><em>Team &ldquo;IT FACTOR&rdquo;</e...,Property Manager,Property Management,True,False,None,None,...,None,None,None,[],[],wyObdVyxxEOkwTIQsnAS3A==,Under Qualified,NaN,declined,False

In [3]:
apps.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110267 entries, 0 to 110266
Data columns (total 24 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   OpportunityId                    110267 non-null  object
 1   ApplicationId                    110267 non-null  object
 2   ExternalBriefDescription         110267 non-null  object
 3   ExternalDescription              110267 non-null  object
 4   Title                            110267 non-null  object
 5   JobCategoryName                  110267 non-null  object
 6   IsRejected                       110267 non-null  bool
 7   IsCandidateInternal              110267 non-null  bool
 8   BehaviorCriteria                 0 non-null       object
 9   MotivationCriteria               0 non-null       object
 10  EducationCriteria                0 non-null       object
 11  LicenseAndCertificationCriteria  2 non-null       object
 12  SkillCriteria                    0 non-null       object
 13  WorkExperiences                  0 non-null       object
 14  Educations                       0 non-null       object
 15  LicenseAndCertifications         0 non-null       object
 16  Skills                           0 non-null       object
 17  Motivations                      2 non-null       object
 18  Behaviors                        2 non-null       object
 19  StepId                           110267 non-null  object
 20  StepName                         110267 non-null  object
 21  Tag                              99394 non-null   float64
 22  StepGroup                        110267 non-null  object
 23  pass_first_step                  110267 non-null  bool
dtypes: bool(3), float64(1), object(20)
memory usage: 18.0+ MB

In [4]:
#Count unique of each column.astype('str') as a dataframe
unique_values_per_column = pd.DataFrame(apps.astype(str).nunique(), columns=['unique'])
unique_values_per_column

                                 unique
OpportunityId                      8473
ApplicationId                    110267
ExternalBriefDescription           1547
ExternalDescription                2761
Title                              2072
JobCategoryName                     128
IsRejected                            2
IsCandidateInternal                   2
BehaviorCriteria                      1
MotivationCriteria                    1
EducationCriteria                     1
LicenseAndCertificationCriteria       2
SkillCriteria                         1
WorkExperiences                       1
Educations                            1
LicenseAndCertifications              1
Skills                                1
Motivations                           2
Behaviors                             2
StepId                              327
StepName                            111
Tag                                   8
StepGroup                             7
pass_first_step                       2

<b>Fields related to opportunities:</b>
- OpportunityId
- ExternalBriefDescription
- Title
- JobCategoryName
- ExternalDescirption

<b>Fields related to applications:</b>
- IsRejected
- IsCandidateInternal
- BehaviorCriteria  [All Null]
- MotivationCriteria [All Null]
- EducationCriteria [All Null]
- LicenseAndCertificationCriteria [All Null]
- SkillCriteria [All Null]
- WorkExperiences [All Null]
- Educations [All Null]
- LicenseAndCertifications [All Null]
- Skills [All Null]
- Motivations [All Null]
- Behaviors [All Null]
- StepId
- StepName
- Tag
- StepGroup
- pass_first_step

### The above apps dataframe has many great opportunities that we can use to understand job descriptions, but applications to them remain null.

### Looking at only the descriptions to see if there are less tokens

In [5]:
descriptions = apps[['ExternalBriefDescription', 'ExternalDescription']]

In [6]:
for column in descriptions.columns:
    descriptions[column + '_len'] = descriptions[column].apply(lambda x: len(x.split()))
descriptions

/var/folders/1w/3dbsn3055ss61n_2tk2w2crm0000gn/T/ipykernel_4516/2602698392.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  descriptions[column + '_len'] = descriptions[column].apply(lambda x: len(x.split()))
/var/folders/1w/3dbsn3055ss61n_2tk2w2crm0000gn/T/ipykernel_4516/2602698392.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  descriptions[column + '_len'] = descriptions[column].apply(lambda x: len(x.split()))

,ExternalBriefDescription,ExternalDescription,ExternalBriefDescription_len,ExternalDescription_len
0,"$16.00 Per Hour\n\nAt Orkin, our purpose is to...",<p><strong>$16.00 Per Hour</strong></p>\n<p><s...,94,440
1,"$15.00 Per Hour\n\nAt Orkin, our purpose is to...",<p><strong>$15.00 Per Hour</strong></p>\n<p><s...,94,440
2,"$15.00 Per Hour\n\nAt Orkin, our purpose is to...",<p><strong>$15.00 Per Hour</strong></p>\n<p><s...,94,440
3,"$15.00 Per Hour\n\nAt Orkin, our purpose is to...",<p><strong>$15.00 Per Hour</strong></p>\n<p><s...,94,440
4,"$15.00 Per Hour\n\nAt Orkin, our purpose is to...",<p><strong>$15.00 Per Hour</strong></p>\n<p><s...,94,440
...,...,...,...,...
110262,Berkshire is a national management company tha...,<p><strong><em>Team &ldquo;IT FACTOR&rdquo;</e...,114,460
110263,Berkshire Communities is a national management...,<p><strong><em>Team &ldquo;IT FACTOR&rdquo;</e...,115,484
110264,Berkshire Communities is a national management...,<p><strong><em>Team &ldquo;IT FACTOR&rdquo;</e...,115,484
110265,Berkshire is a national management company tha...,<p><strong><em>Team &ldquo;IT FACTOR&rdquo;</e...,127,475
110266,Berkshire Communities is a national management...,<p><strong><em>Team &ldquo;IT FACTOR&rdquo;</e...,115,484

In [7]:
descriptions[['ExternalBriefDescription_len', 'ExternalDescription_len']].describe()

       ExternalBriefDescription_len  ExternalDescription_len
count                 110267.000000            110267.000000
mean                      79.592652               478.722809
std                       22.832749               251.857718
min                        3.000000                 4.000000
25%                       75.000000               426.000000
50%                       80.000000               456.000000
75%                       91.000000               495.000000
max                      141.000000              3935.000000

In [11]:
applicant_columns = ['ApplicationId', 'dateAppliedAt', 'JobTitle', "WhatYouDid", "LicenseAndCertification",
                     "major", "degree", "skill",
                     'IsCandidateInternal', 'IsRejected']

opportunity_columns = ['OpportunityId', 'Title', 'ExternalBriefDescription', 'ExternalDescription', 'JobCategoryName']

In [12]:
# pick a random ApplicationId and use apps.loc to get the rows for that application.
random_applicationId = random.choice(apps['ApplicationId'])
apps.loc[apps['ApplicationId'] == random_applicationId]

,OpportunityId,ApplicationId,ExternalBriefDescription,ExternalDescription,Title,JobCategoryName,IsRejected,IsCandidateInternal,BehaviorCriteria,MotivationCriteria,...,Educations,LicenseAndCertifications,Skills,Motivations,Behaviors,StepId,StepName,Tag,StepGroup,pass_first_step
48465,zUXLYdPiz0KurPlsTZM92g==,K5HANWwkpEKw25ZdPPsPgA==,"At Orkin, our purpose is to help protect the w...","<p><strong>At Orkin, our purpose is to help pr...",Region Manager,Operations Leadership,True,False,None,None,...,None,None,None,None,None,K8yQlic+/UiXxBMpOnAoLQ==,Decline,2.0,declined,False

In [13]:
apps[["IsRejected",	"IsCandidateInternal",	"StepId",	"StepName",	"Tag",	"StepGroup",	"pass_first_step",]].nunique()

IsRejected               2
IsCandidateInternal      2
StepId                 327
StepName               111
Tag                      7
StepGroup                7
pass_first_step          2
dtype: int64

In [14]:
[i for i in apps.Tag.unique()]

[2.0, 3.0, 5.0, 6.0, 1.0, nan, 4.0, 7.0]

In [15]:
[i for i in apps.StepGroup.unique()]

['declined',
 'interview',
 'background_check',
 'other',
 'hired',
 'screen',
 'references']

## All the applicant data is null, so we cannot utilize this to predict applicant/opportunity compatability